name: Build, Test, and Push Docker Image

on:
  push:
    branches: ["main"]
    tags: ['v*.*.*']

env:
  REGISTRY: docker.io
  #IMAGE_NAME: dipakrasal2009/github-action-docker

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false  # Build only, don’t push yet
          tags: dipakrasal2009/github-action-docker:latest

      - name: Run tests inside Docker container
        run: |
          docker run --rm dipakrasal2009/github-action-docker:latest pytest test_app.py

      - name: Push Docker image
        if: success()  # Push only if tests pass
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dipakrasal2009/github-action-docker:latest

